baseURL = "http://www.example.com"
title = "Matthiswieneke"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Matthis Wieneke"
description = "Matthis Wieneke's personal website"
keywords = "blog,developer,personal"
info = ["Full Stack Software Engineer", "Amateur photographer"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/kellermatthis/"

[[params.social]]
name = "Xing"
icon = "fa fa-2x fa-xing"
weight = 3
url = "https://www.xing.com/profile/Matthis_Wieneke/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/matthis-wieneke-a617a2218/"

[[params.social]]
name = "Industrial Portfolio"
icon = "fa fa-2x fa-camera"
weight = 4
url = "https://industrial-portfolio.de/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.de]
languageName = ":de:"
title = "Matthiswieneke"

[languages.de.params]
author = "Matthis Wieneke"
info = ["Full Stack Softwareentwickler", "Hobbyfotograf"]
description = "Die Webseite von Matthis Wieneke"
keywords = "Blog,Softwareentwickler,Persönliches"

[[languages.de.menu.main]]
name = "Über mich"
weight = 1
url = "about/"

[[languages.de.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.de.menu.main]]
name = "Projekte"
weight = 3
url = "projects/"

[[languages.de.menu.main]]
name = "Kontakt"
weight = 5
url = "contact/"